apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fiter-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/leomax060778/argocd-poc
        revision: HEAD
        files:
          - path: poc2/apps/**/kustomization.yml
  template:
    metadata:
      name: '{{.cluster.name}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/leomax060778/argocd-poc
        targetRevision: HEAD
        path: poc2/apps/
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc