apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fiterApp
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/leomax060778/argocd-poc
        revision: HEAD
        directories:
          - path: poc2/apps/*/*
  template:
    metadata:
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/leomax060778/argocd-poc
        targetRevision: HEAD
        path: poc2/apps/{{path[2]}}/{{path.basename}}/{{name}}
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc