# Default values for sample-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 916148231619.dkr.ecr.us-east-2.amazonaws.com/latam-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  TZ: "UTC"
  FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME: "com.mariadb.jdbc.Driver"
  FINERACT_HIKARI_JDBC_URL: "jdbc:mariadb://mariadb-cluster:3306/fineract_tenants"
  FINERACT_HIKARI_USERNAME: "root"
  FINERACT_HIKARI_MINIMUM_IDLE: 1
  FINERACT_HIKARI_MAXIMUM_POOL_SIZE: 20
  FINERACT_HIKARI_IDLE_TIMEOUT: 120000
  FINERACT_HIKARI_CONNECTION_TIMEOUT: 300000
  FINERACT_HIKARI_TEST_QUERY: "SELECT 1"
  FINERACT_HIKARI_AUTO_COMMIT: "true"
  FINERACT_HIKARI_DS_PROPERTIES_CACHE_PREP_STMTS: "true"
  FINERACT_HIKARI_DS_PROPERTIES_PREP_STMT_CACHE_SIZE: 250
  FINERACT_HIKARI_DS_PROPERTIES_PREP_STMT_CACHE_SQL_LIMIT: 2048
  FINERACT_HIKARI_DS_PROPERTIES_USE_SERVER_PREP_STMTS: "true"
  FINERACT_HIKARI_DS_PROPERTIES_USE_LOCAL_SESSION_STATE: "true"
  FINERACT_HIKARI_DS_PROPERTIES_REWRITE_BATCHED_STATEMENTS: "true"
  FINERACT_HIKARI_DS_PROPERTIES_CACHE_RESULT_SET_METADATA: "true"
  FINERACT_HIKARI_DS_PROPERTIES_CACHE_SERVER_CONFIGURATION: "true"
  FINERACT_HIKARI_DS_PROPERTIES_ELIDE_SET_AUTO_COMMITS: "true"
  FINERACT_HIKARI_DS_PROPERTIES_MAINTAIN_TIME_STATS: "false"
  FINERACT_HIKARI_DS_PROPERTIES_LOG_SLOW_QUERIES: "true"
  FINERACT_HIKARI_DS_PROPERTIES_DUMP_QUERIES_IN_EXCEPTION: "true"
  FINERACT_DEFAULT_TENANTDB_HOSTNAME: "mariadb-cluster"
  FINERACT_DEFAULT_TENANTDB_PORT: 3306
  FINERACT_DEFAULT_TENANTDB_UID: "admin"
  FINERACT_DEFAULT_TENANTDB_TIMEZONE: "Europe/London"
  FINERACT_DEFAULT_TENANTDB_IDENTIFIER: "default"
  FINERACT_DEFAULT_TENANTDB_NAME: "fineract_default"
  FINERACT_DEFAULT_TENANTDB_DESCRIPTION: "Latam Fineract Default Tenant"
  FINERACT_SERVER_SSL_ENABLED: "true"
  FINERACT_SERVER_PORT: 8443
  FINERACT_HIKARI_PASSWORD: "mysql"
  FINERACT_DEFAULT_TENANTDB_PWD: "mysql"

service:
  type: ClusterIP
  servicePorts:
    - port: 8080
      containerPort: 8080
      protocol: TCP
      name: http
    - port: 8443
      containerPort: 8443
      protocol: TCP
      name: job-port
      # service_disabled: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  serviceAccount:
    name: application-sa
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 1024m
      memory: 2048Mi
    limits:
      cpu: 2048m
      memory: 3096Mi

## Application level settings  
appMode: dev
certificatePath: /etc/ssl/dev
paypalURLLocation: https://dev.paypal.example.com
databaseUser: dev-user
databasePassword: dev-password




