apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fineract-rest-ui
    app.kubernetes.io/instance: mifos
    tier: frontend
  name: fineract-rest-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fineract-rest-ui
  template:
    metadata:
      labels:
        app: fineract-rest-ui
    spec:
      containers:
        - env:
            - name: FINERACT_DOMAIN
              value: ''
            - name: FINERACT_BASE_URL
              value: /fineract-provider/api/v1
            - name: FINERACT_PROXY_URL
              value: 'https://fineract-rest:8443'
            - name: DOLLAR
              value: $
          image: 'leonardohildt/mifos-app:727677a'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
          name: fineract-rest-ui
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
