apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: mifos

resources:
  - namespace.yaml
  - deployment.yml
  - service.yml

images:
  - name: leonardohildt/mifos-app
    newTag: 727677a