apiVersion: v1
kind: Service
metadata:
  name: mifos
  namespace: mifos
  labels:
    app: mifos
    tier: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  selector:
    app: mifos
    tier: frontend
    instance: mifos