apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-argo-common-chart
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/leomax060778/argocd-poc
        revision: HEAD
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: poc2/apps/*
  template:
    metadata:
      namespace: argocd
      # you can use the path strings with / delimiter as variables
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/leomax060778/argocd-poc
        targetRevision: HEAD
        path: poc2
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      destination:
        # specify different destinations
        namespace: "{{path.basename}}"
        server: https://kubernetes.default.svc
